#pragma once

#define MATRIX_WIDTH 9
#define MATRIX_HEIGHT 5

#define PIN_POWER 6
#define PORT_POWER PORTB
#define DDR_POWER DDRB

#define PIN_BUTT1 1
#define PORT_BUTT1 PORTB
#define INPUT_BUTT1 PINB
#define DDR_BUTT1 DDRB

#define PIN_BUTT2 2
#define PORT_BUTT2 PORTB
#define INPUT_BUTT2 PINB
#define DDR_BUTT2 DDRB

#define PIN_SHUTTER 0
#define PORT_SHUTTER PORTB
#define DDR_SHUTTER DDRB

